<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>New service request</title>
</head>
<body style="margin:0;padding:0;background:#f1f5f9;font-family:'Helvetica Neue',Helvetica,Arial,sans-serif;color:#0f172a;">

<table width="100%" cellpadding="0" cellspacing="0" style="background:#f1f5f9;padding:40px 16px;">
  <tr>
    <td align="center">
      <table width="100%" cellpadding="0" cellspacing="0" style="max-width:560px;">

        {{-- Header --}}
        <tr>
          <td style="background:#0f172a;border-radius:16px 16px 0 0;padding:32px 40px;">
            <p style="margin:0;font-size:11px;font-weight:800;letter-spacing:.2em;text-transform:uppercase;color:#94a3b8;">
              {{ $inquiry->company?->short_name ?? $inquiry->company?->name ?? 'BluePrint Group' }}
            </p>
            <h1 style="margin:10px 0 0;font-size:22px;font-weight:900;color:#ffffff;line-height:1.2;">New Service Request</h1>
            <p style="margin:8px 0 0;font-size:13px;color:#94a3b8;">Submitted {{ now()->format('D, d M Y \a\t H:i') }}</p>
          </td>
        </tr>

        {{-- Alert band --}}
        <tr>
          <td style="background:#fefce8;border-left:4px solid #eab308;padding:14px 28px;">
            <p style="margin:0;font-size:13px;font-weight:700;color:#713f12;">
              Action required — please respond to this inquiry as soon as possible.
            </p>
          </td>
        </tr>

        {{-- Body --}}
        <tr>
          <td style="background:#ffffff;padding:36px 40px;">

            {{-- Client details --}}
            <p style="margin:0 0 16px;font-size:10px;font-weight:800;letter-spacing:.18em;text-transform:uppercase;color:#94a3b8;">Client details</p>
            <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;margin-bottom:24px;">
              <tr>
                <td style="padding:20px 24px;">
                  <p style="margin:0;font-size:15px;font-weight:800;color:#0f172a;">{{ $inquiry->name }}</p>
                  <p style="margin:6px 0 0;font-size:13px;color:#475569;line-height:1.8;">
                    <strong>Phone:</strong>
                    <a href="tel:{{ $inquiry->phone }}" style="color:#073B7A;">{{ $inquiry->phone }}</a><br>
                    @if($inquiry->email)
                    <strong>Email:</strong>
                    <a href="mailto:{{ $inquiry->email }}" style="color:#073B7A;">{{ $inquiry->email }}</a><br>
                    @endif
                    @if($inquiry->organization)
                    <strong>Organization:</strong> {{ $inquiry->organization }}
                    @endif
                  </p>
                </td>
              </tr>
            </table>

            {{-- Request details --}}
            <p style="margin:0 0 16px;font-size:10px;font-weight:800;letter-spacing:.18em;text-transform:uppercase;color:#94a3b8;">Request details</p>
            <table width="100%" cellpadding="0" cellspacing="0" style="background:#f8fafc;border:1px solid #e2e8f0;border-radius:12px;margin-bottom:28px;">
              <tr>
                <td style="padding:20px 24px;">
                  @if($inquiry->subject)
                  <p style="margin:0 0 10px;font-size:14px;font-weight:700;color:#0f172a;">{{ $inquiry->subject }}</p>
                  @endif
                  <p style="margin:0;font-size:13px;line-height:1.8;color:#334155;">{{ $inquiry->message }}</p>
                </td>
              </tr>
            </table>

            {{-- CTA --}}
            <p style="margin:0 0 20px;font-size:14px;line-height:1.7;color:#475569;">
              Log in to the admin panel to view and respond to this inquiry.
            </p>
            <a href="{{ config('app.url') }}/admin/inquiries" style="display:inline-block;background:#073B7A;color:#ffffff;text-decoration:none;font-size:13px;font-weight:800;padding:14px 28px;border-radius:50px;">
              View inquiry in admin →
            </a>
          </td>
        </tr>

        {{-- Footer --}}
        <tr>
          <td style="background:#f8fafc;border-top:1px solid #e2e8f0;border-radius:0 0 16px 16px;padding:24px 40px;text-align:center;">
            <p style="margin:0;font-size:12px;color:#94a3b8;line-height:1.7;">
              This message was automatically generated by the BluePrint website.<br>
              &copy; {{ date('Y') }} BluePrint Group. All rights reserved.
            </p>
          </td>
        </tr>

      </table>
    </td>
  </tr>
</table>

</body>
</html>
